spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:client
    username : admin
    password: admin
  h2:
    console:
      enabled: true
logging:
  level:
    com:
      client: INFO
server:
  port: 8090
  servlet:
    context-path: /api
#springdoc:
#  swagger-ui:
#    path=/swagger-ui:
#      html: /swagger-ui.html
