-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table cliente
CREATE TABLE cliente (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(255),
    apellidos            VARCHAR(255),
    numero_identificacion VARCHAR(255),
    creditos            NUMERIC(38,2)
);

---- changeset script:2
---- comment: Creation table estado_transaccion
CREATE TABLE estado_transaccion (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(255),
    estado      VARCHAR(255)
);

---- changeset script:3
---- comment: Creation table fondo
CREATE TABLE fondo (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(255),
    categoria        VARCHAR(255),
    monto_vinculacion NUMERIC(38,2)
);

---- changeset script:4
---- comment: Creation table transaccion
CREATE TABLE transaccion (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha                   TIMESTAMP(6),
    cliente_fk              INTEGER,
    estado_transaccion_fk   INTEGER,
    fondo_fk        INTEGER,
    CONSTRAINT fk_transaccion_cliente
        FOREIGN KEY (cliente_fk)
        REFERENCES cliente (id),
    CONSTRAINT fk_transaccion_estado
        FOREIGN KEY (estado_transaccion_fk)
        REFERENCES estado_transaccion (id),
    CONSTRAINT fk_transaccion_fondo
        FOREIGN KEY (fondo_fk)
        REFERENCES fondo (id)
);
--
alter table if exists cliente drop constraint if exists UK2iwc2v1bwcqs5ofr4e7brqo4s;
alter table if exists cliente add constraint UK2iwc2v1bwcqs5ofr4e7brqo4s unique (numero_identificacion);
alter table if exists transaccion add constraint FK8gl5g2fvobe8gx62an46c9egu foreign key (cliente_fk) references cliente;
alter table if exists transaccion add constraint FK95d2koqwahqj5j1mdpe9gkv6k foreign key (estado_transaccion_fk) references estado_transaccion;
alter table if exists transaccion add constraint FKdyjr0kv58bbl3gymfdukr00nn foreign key (fondo_fk) references fondo;

-- changeset script:10
-- comment: INSERT INTO table estado_transaccion
INSERT INTO estado_transaccion (descripcion, estado) VALUES
('Apertura de la suscripcion', 'APERTURA'),
('Cancelación de la suscripcion', 'CANCELAR');

-- changeset script:11
-- comment: INSERT INTO table cliente
INSERT INTO cliente (
    nombre,
    apellidos,
    numero_identificacion,
    creditos
) VALUES (
    'Juan',
    'Pérez',
    '123456789',
    500000.00
);

-- changeset script:12
-- comment: INSERT INTO table fondo
INSERT INTO fondo (id, nombre, monto_vinculacion, categoria) VALUES
(1, 'FPV_BTG_PACTUAL_RECAUDADORA', 75000.00, 'FPV'),
(2, 'FPV_BTG_PACTUAL_ECOPETROL',   125000.00, 'FPV'),
(3, 'DEUDAPRIVADA',                 50000.00, 'FIC'),
(4, 'FDO-ACCIONES',                250000.00, 'FIC'),
(5, 'FPV_BTG_PACTUAL_DINAMICA',    100000.00, 'FPV');

